basePath:
dictionary:
- name: "product"
  type: "SYSTEM"
  filePath: "dict/product.dict"
  ignoreCase: true
- name: "user"
  type: "SET"
  tokenType: "MAX"
  source: "es://.fastcatx_dict"
  filePath: "dict/user.dict"
  ignoreCase: true
- name: "synonym"
  type: "SYNONYM"
  tokenType: "NONE"
  source: "es://.fastcatx_dict"
  filePath: "dict/synonym.dict"
  ignoreCase: true
- name: "stop"
  type: "SET"
  tokenType: "MAX"
  source: "es://.fastcatx_dict"
  filePath: "dict/stop.dict"
  ignoreCase: true
- name: "space"
  type: "SPACE"
  tokenType: "MIN"
  source: "es://.fastcatx_dict"
  filePath: "dict/space.dict"
  ignoreCase: true
- name: "compound"
  type: "COMPOUND"
  tokenType: "MID"
  source: "es://.fastcatx_dict"
  filePath: "dict/compound.dict"
  ignoreCase: true
- name: "unit"
  type: "SET"
  tokenType: "HIGH"
  source: "es://.fastcatx_dict"
  filePath: "dict/unit.dict"
  ignoreCase: true
- name: "unit_synonym"
  type: "SYNONYM_2WAY"
  tokenType: "HIGH"
  source: "es://.fastcatx_dict"
  filePath: "dict/unit_synonym.dict"
  ignoreCase: true
- name: "maker"
  type: "CUSTOM"
  tokenType: "NONE"
  source: "es://.fastcatx_dict"
  filePath: "dict/maker.dict"
  ignoreCase: true
- name: "brand"
  type: "CUSTOM"
  tokenType: "NONE"
  source: "es://.fastcatx_dict"
  filePath: "dict/brand.dict"
  ignoreCase: true
- name: "category"
  type: "CUSTOM"
  tokenType: "NONE"
  source: "es://.fastcatx_dict"
  filePath: "dict/category.dict"
  ignoreCase: true
- name: "english"
  type: "SET"
  tokenType: "MAX"
  source: "es://.fastcatx_dict"
  filePath: "dict/english.dict"
  ignoreCase: true